version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - default

  database:
    container_name: chain_sharp_database
    image: postgres
    restart: always
    shm_size: 512m
    environment:
      POSTGRES_USER: chain_sharp
      POSTGRES_PASSWORD: chain_sharp123 
      POSTGRES_DB: chain_sharp
    tty: true
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
